### ISSUE TITLE
Make jqwik-vavr a module of jqwik itself

### ISSUE THREAD

**Issue by jlink** [jqwik-team/jqwik-vavr#10]
@Befrish If you are interested we could include` jqwik-vavr` as an "official" jqwik module.

Two options:
- With its own versioning policy, like `jqwik-spring` or `jqwik-testcontainers`
- Synchronized with jqwik core versioning, like `jqwik-time`, `jqwik-web` and `jqwik-kotlin`

The latter option requires more synchronisation and constant update, of course.

**Comment by Befrish** [comment]
Hi @jlink ,
it is a nice idea. I'm interested in providing this as an "official" jqwik module.

I think it the first option is a little bit better in order get more flexibility with the external dependency to Vavr. You can react faster to support newer versions of Vavr.

What would you suggest in order to migration this projecct to "official" repository?

**Comment by jlink** [comment]
@Befrish 
The simplest first step would not even require an "official" repository. All modules that are currently published under "net.jqwik" have their repo in my user, but that's not really necessary. I could (or maybe should) create a jqwik organisation on Github one of these days, then all repos can move there. If you want, though, the initial repo can be under my user, of course.

To do the migration I suggest taking https://github.com/jlink/jqwik-spring as a template.  So there are a few steps:
1. Move from Maven to Gradle. That's not strictly necessary but I personally don't want to support diverging approaches for building, deploying and releasing artefacts. I also suggest starting with a new version number, maybe `2.0.0` in order to make the jump obvious.
2. Change base package to `net.jqwik.vavr` and move all published API to `net.jqwik.vavr.api`.
3. Add `org.apiguardian.api.API` annotations to the published part of the API.
4. Add a little bit of documentation for the supported generation DSL `VavrAbitraries` etc. and compatibility with Vavr and jqwik versions.
5. First release by me
6. Find an easy way to allow you to release as well. This probably requires generating release tokens. One could also move the release process to GitHub actions if that will simplify things.

I can help with most steps, but apart from 5 and 6, I don't have to.

I haven't looked deeply into the current code so there may be a few things that should be changed to make the API align with current APIs. 

As for the frequency of updates: IMO the minimum should be to keep up compatibility with the latest jqwik release. For instance, I noticed the use of `@Unique` annotation somewhere, which is no longer supported.

**Comment by Befrish** [comment]
@jlink I have committed some changes. I updated the versions to the latest. This commits should cover most of the points. Regarding annotating API and documentation I'am not finished yet. By change you can have a deeper look in the code and give me some feedback.

Note: I added Gradle files in order to support your wish.  But I want to leave Maven, because the Gradle plugins does not support all of the features I use in Maven. These features are import to ensure the quality. So I will use Maven in future development. The build with Gradle should work without problem, because it does less tasks than Maven.

**Comment by jlink** [comment]
Looks good at first glance. 
I’ll publish a snapshot and create a PR with some minor suggestions.

**Comment by jlink** [comment]
Added PR https://github.com/Befrish/jqwik-vavr/pull/12

**Comment by jlink** [comment]
Published successfully to "2.0.0-SNAPSHOT"

**Comment by jlink** [comment]
Documentation is wrong. Group ID is "net.jqwik" not "net.jqwik.vavr"

**Comment by Befrish** [comment]
I fixed the groupId in the documentation.

**Comment by jlink** [comment]
If you’re happy with the current state I could do a first release. Documentation can always be improved later. 

Two options: you either give me write access to the repo so that I can advance version numbers to 2.0.0 and after publication to 2.0.1-SNAPSHOT, or you create the release version, tag it and tell me when you’re done. I can checkout the tag and publish the release. Both are fine for me.

**Comment by jlink** [comment]
Maybe you also want to add a sample to https://github.com/jlink/jqwik-samples

**Comment by jlink** [comment]
I created an organisation for all jqwik-related development: https://github.com/jqwik-team/

@Befrish If you want, you can transfer the repo there and I'll add you as collaborator/maintainer.

Also, I'd like to release 2.0.0 if you give your ok. Mid-term I plan to set-up a release-mechanism that can be triggered by all maintainers - probably via a GH action.

**Comment by Befrish** [comment]
@jlink This is okay. Please give me the permission to create a repository in the organisation. Then I can transfer the repository.

**Comment by jlink** [comment]
@Befrish I sent out an invitation

**Comment by Befrish** [comment]
@jlink Thank you. I transfered the repository. I think there are some adjustments to do (Maven Repository, Readme-File with Repository in text).

**Comment by jlink** [comment]
@Befrish Will you do the adjustments or should I?

**Comment by Befrish** [comment]
@jlink I do not have enough time to do this at the moment. So you can do it.

**Comment by jlink** [comment]
2.0.0 has been released
