### ISSUE TITLE
Upgrade to latest jqwik version

### ISSUE THREAD

**Issue by jlink** [jqwik-team/jqwik-vavr#15]
The current version 2.0.0 of jqwik-vavr is not compatible with jqwik >= 1.7.0

Two options:
- Upgrade to jqwik >= 1.7.0, which is mostly straightforward
- Upgrade to jqwik 1.7.3 (the next release). This can fix the shortcomings of current handling of `@UniqueElements` annotation, but is incompatible with jqwik <= 1.7.2

**Comment by Befrish** [comment]
@jlink We can take #17 instead.
