### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by dlesl** [jqwik-team/jqwik-vavr#18]
Hi! Thanks for the excellent library. Just wondering if there are any plans to publish this?

**Comment by jlink** [comment]
It has been on Maven Central for a few months now: https://mvnrepository.com/artifact/net.jqwik/jqwik-vavr.
This should be clear from https://github.com/jqwik-team/jqwik-vavr/blob/master/README.md. Is it not?

**Comment by dlesl** [comment]
Ah sorry, my mistake! When I searched [mvnrepository](https://mvnrepository.com/search?q=jqwik-vavr) it didn't appear on the first page of results, and then I found the [packages](https://github.com/jqwik-team/jqwik-vavr/packages/428739) page on github which refers to what I guess are old coordinates (de.befrish.jqwik) which I also couldn't find on maven, I didn't make it to the end of the README unfortunately 😁
